version: "3"
services:
  client:
    build:
      context: './client'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: bookClient
    networks:
      - mern-network
    volumes:
      - ./client:/client
    depends_on:
      - server
  server:
    build:
      context: './server'
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    container_name: bookServer
    networks:
      - mern-network
    volumes:
      - ./server:/server
networks:
  mern-network:
